#!/bin/bash

wget --load-cookies $1 "https://connect.garmin.com/modern/proxy/activitylist-service/activities/search/activities?limit=1500&start=0" -O $1.json 2> /tmp/wget_out 
grep ERROR\  /tmp/wget_out 
rm -f /tmp/wget_out

if [ -f $1.json ]; then 

	if [ ! -f $1.db ]; then
		>  $1.db
		echo "activityId, activityName, startTimeLocal, activityType, Distance (km), Time (min), Elapsed Time (ms), Moving Time (s), Elevation Gain (m), Elevation Loss (m), averageSpeed, maxSpeed, calories, averageHR, maxHR, timeZoneId, beginTimestamp, sportTypeId, deviceId, Min. Elevation, Max. Elevation, maxVerticalSpeed, locationName, lapCount, minActivityLapDuration" > $1.csv
	fi
	
	jq '.[] | .activityId' $1.json | sort > $1.latest
	comm -3 --output-delimiter=+ $1.db $1.latest | cut -d"+" -f2 > $1.delta

	if [ -s $1.delta ]; then
		for a in `cat $1.delta` 
		do
			wget -q --load-cookies $1 "https://connect.garmin.com/modern/proxy/download-service/export/gpx/activity/$a" 
			if [ -s $a ]; then
				epoch=`jq -r ".[] | select(.activityId==$a) | .beginTimestamp/1000" $1.json`
				datum=`date -d @${epoch} +"%Y%m%d"`
				sport=`jq -r ".[] | select(.activityId==$a) | .activityType.typeKey" $1.json`
				mv $a ${datum}_${a}_${sport}.gpx
				jq ".[] | select(.activityId==$a)" $1.json | jq -r ' [.activityId,.activityName,.startTimeLocal,.activityType.typeKey,.distance/1000,.duration/60,.elapsedDuration,.movingDuration,.elevationGain,.elevationLoss,.averageSpeed,.maxSpeed,.calories,.averageHR,.maxHR,.timeZoneId,.beginTimestamp,.sportTypeId,.deviceId,.minElevation,.maxElevation,.maxVerticalSpeed,.locationName,.lapCount,.minActivityLapDuration] | @csv' >> $1.csv
				echo -n "."
			else
				echo -n '{error:'$a'}'
				sed '/'$a'/d' $1.latest > $1.latest_
				mv $1.latest_  $1.latest
			fi
		done
		echo "."
		count=`cat $1.delta | wc -l`
		echo "$count activities found."
	else
		echo "No new activities"
	fi

	mv $1.latest $1.db
	rm -f $1.delta $1.downloaded $1.json

fi


