#!/bin/bash

wget --load-cookies $1 "https://connect.garmin.com/modern/proxy/activitylist-service/activities/search/activities?limit=1500&start=0" -O $1.json 2> /tmp/wget_out 
grep ERROR\  /tmp/wget_out 
rm -f /tmp/wget_out

if [ -f $1.json ]; then 

	if [ ! -f $1.db ]; then
		>  $1.db
	fi
	
	jq '.[] | .activityId' $1.json | sort > $1.latest
	comm -3 --output-delimiter=+ $1.db $1.latest | cut -d"+" -f2 > $1.delta

	if [ -s $1.delta ]; then
		for a in `cat $1.delta` 
		do
			wget -q --load-cookies $1 "https://connect.garmin.com/modern/proxy/download-service/export/gpx/activity/$a" 
			if [ -s $a ]; then
				datum=`cat $a | grep "<time>" | head -1 | cut -d">" -f2 | cut -d"T" -f1`
				garnr=`echo $a | cut -d'.' -f1 | cut -d"_" -f2`
				sport=`cat $a |  grep "<type>" | cut -d">" -f2 | cut -d"<" -f1`
				mv $a ${datum}_${garnr}_${sport}.gpx
				echo -n "."
			else
				echo -n '{error:'$a'}'
				sed '/'$a'/d' $1.latest > $1.latest_
				mv $1.latest_  $1.latest
			fi
		done
		echo "."
		count=`cat $1.delta | wc -l`
		echo "$count activities found."
	else
		echo "No new activities"
	fi

	mv $1.latest $1.db
	rm -f $1.delta $1.downloaded $1.json

fi


